### ISSUE TITLE
Synchronization not active anymore

### ISSUE THREAD

**Issue by cmorty** [kaos/ecos#1]
It seems like the synchronization with http://hg-pub.ecoscentric.com/ecos/ is not working any more.

**Comment by kaos** [comment]
True. I should remove that comment.

**Comment by kaos** [comment]
It hasn't been syncing for years (since 2012 it seems..)
Haven't used it since about then...

**Comment by cmorty** [comment]
I was hoping for: "Ah yes, I just fixed it." It seems like I'll just have to learn hg. ;)

**Comment by kaos** [comment]
Sorry to disappoint you ;)
If you're having real problems with it, I may be able to boot up my old jet
monster for server and look for the cron job I had going..

sön 10 apr. 2016 kl. 21:03 skrev Moritz Strübe notifications@github.com:
